apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: {{ .Values.jenkins.namespace }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jenkins.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "jenkins.labels" . | nindent 8 }}

    spec:
      containers:
        - name: jenkins
          image: {{ .Values.jenkins.image.repository }}:{{ .Values.jenkins.image.tag }}
          imagePullPolicy: {{ .Values.jenkins.image.pullPolicy }}
          env:
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: jenkins-secret
                  key: password
            - name: JAVA_OPTS
              value: "-Djenkins.install.runSetupWizard=false"
            - name: CASC_JENKINS_CONFIG
              value: /var/jenkins_home/casc_configs/jenkins.yaml
          ports:
            - name: http-port
              containerPort: {{ .Values.service.port }}
            - name: jnlp-port
              containerPort: {{ .Values.slave.port }}
          resources:
            {{- toYaml .Values.jenkins.resources | nindent 12 }}
          volumeMounts:
            - name: jenkins-auth-config
              mountPath: /var/jenkins_home/init.groovy.d/basic-security.groovy
              subPath: basic-security.groovy
            - name: jenkins-config-yaml
              mountPath: /var/jenkins_home/casc_configs/jenkins.yaml
              subPath: jenkins.yaml
            - name: jenkins-config
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-auth-config
          configMap:
            name: basic-security
        - name: jenkins-config-yaml
          configMap:
            name: jenkins-config
        - name: jenkins-config
          nfs:
            server: {{ .Values.jenkins.persistence.nfs.server }}
            path: {{ .Values.jenkins.persistence.nfs.path }}


