apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.jenkins.namespace }}
  name: {{ include "jenkins.fullname" . }}
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-port
      protocol: TCP
      name: http-port
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}
